### PR TITLE
Ruby on Rails capstone project - Budget app

### PR DESCRIPTION
**Pull request by WilhelmK109**
### In this project, I did the following:
- Used Postgres as my database.
- Splash screen: Created a simple page with the name of the app, with links to the sign up and log in pages.
- Created a Sign up and log in pages.
- The user should be able to register in the app with full name, email and password (all mandatory).
- Authenticate and authorize users
- Created the categories page.
- Created the Transactions page
- Created forms to allow a user to create a new category
- Created a new transaction page
- Created unit and integration tests for the most important components of the RoR application.
- Used devise for authentication.
- Validate all user input to make sure that anyone with bad intentions cannot compromise the app.
- Used erb view template engine.
- Deployed the project to render.

### CODE REVIEW

**Review by muneebulrehman — CHANGES_REQUESTED** [review]
Hi @WilhelmK109 , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR
- Good UI
- Clean code

## Required Changes ♻️
_Check the comments under the review._

- [ ] While creating a transaction inside a category, each transaction is created twice. Kindly fix this issue.
https://github.com/WilhelmK109/ror-budget-app/assets/33268927/189ffb89-bbc3-44e0-8852-286364bbe806

- [ ] As per the project requirement, you should record a video presentation following the below guidelines. Kindly record a video presentation and add the link to your README file before submitting for a re-review.
image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by WilhelmK109** [comment]
@muneebulrehman, Thank you very much for your comments and suggestions. I will make the required changes and resubmit for review.

**Review by tufoinnkuo10 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @WilhelmK109 

Your project is complete! Great job for Taking out time to make the previous reviewers' changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍✔️✔️
- Descriptive Pull Request✔️✔️
- The app works as expected✔️✔️
- Wireframe design well followed✔️✔️
- Work well presented✔️✔️
- Database ok✔️✔️
- No linter errors✔️✔️


## Video presentation
--- please always ensure to give a general idea of your project, why you created it, and how important it is going to be. nice job
<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 


nice

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by WilhelmK109** [comment]
@tufoinnkuo10, thank you very much, sir.

**Pull request merged**
